### ISSUE TITLE
Debug failing tests 

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-datalabeling#53] opened 2020-11-16 22:59 UTC
Transferred from https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3759

> We will disable `label_text_test.py::test_label_text` and `manage_dataset_test.py::test_list_dataset` in `datalabeling` directory.
> 
> [Failed build ](https://source.cloud.google.com/results/invocations/cf30940a-c7ec-43be-a9f6-6f413b5fb22b/targets/github%2Fpython-docs-samples%2Fdatalabeling/tests)
> 
> It seems like
> 
> * the dataset is considered empty for `label_text_test.py::test_label_text`.
> * the test backend is throwing DeadlineExceeded for `manage_dataset_test.py::test_list_dataset`.
> 
> This bug is to debug them and re-enable them if possible.

**Comment by parthea** [comment] 2023-04-15 15:21
Closing as duplicate of https://github.com/GoogleCloudPlatform/python-docs-samples/issues/9644

**Closed by parthea** 2023-04-15 15:21 UTC
Labels: type: cleanup, api: datalabeling
